---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
 name: ais-topic 
 labels:
   strimzi.io/cluster: "ais-cluster"
spec:
  partitions: 1
  replicas: 1
  config:
    max.request.size: 2706096
    message.max.bytes: 5000000
    replica.fetch.max.bytes: 5000000

