apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: ais-connect-cluster
spec:
  replicas: 1
  bootstrapServers: ais-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: ais-cluster-cluster-ca-cert
        certificate: ca.crt
