---

- name: Check for supported version
  fail:
    msg: "Please use a supported OS, detected: {{ ansible_distribution }}"
  when: ansible_distribution != "RedHat"

- name: Install libreswan
  yum:
    name: libreswan
    state: latest

