---

- name: Initialize IPSec nss
  shell: ipsec initnss

- name: Import Certificate
  shell: pk12util -i /root/certs.p12 -d sql:/etc/ipsec.d -W ""

#- name: Remove Certificate
#rm -f /root/certs.p12




